name: Measure Code Coverage
on: [ pull_request ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      # Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Run coverage
      - name: Run Coverage
        run: ./gradlew jacocoTestCoverageVerification

      # Update Readme Badge
      - name: Update Readme Badge
        uses: cicirello/jacoco-badge-generator@v2.8.1